### PR TITLE
Add AppStream metadata

### PR DESCRIPTION
**Pull request by Mailaender**
required for https://github.com/acreloaded/acr/issues/264

### CODE REVIEW

**Comment by theonlypwner** [comment]
I'm not that familiar with Flatpak, so I have these questions:

Something similar seems to have been set up for AC (flathub/flathub#3221 and [flathub/net.cubers.assault.AssaultCube](https://github.com/flathub/net.cubers.assault.AssaultCube)), without requiring files to be added to the main repo at [assaultcube/AC](https://github.com/assaultcube/AC). Is there something different about how it needs to be set up for ACR? Is the idea to allow ACR to update the metadata directly in the main repo instead of having to update another repo?

When compared to other Flatpak apps, does this manifest belong in the main repo or in the other repo [flathub/ca.victorz.acr.AssaultCubeReloaded](https://github.com/flathub/ca.victorz.acr.AssaultCubeReloaded)?

The `/packages` folders from AC are distributed under the same license as AC, which requires them to be distributed in their entirety without modifications. Should `<project_license>` in `ca.victorz.acr.AssaultCubeReloaded.appdata.xml` be updated to be the same as the value in `net.cubers.assault.AssaultCube.appdata.xml` to reflect this?

**Comment by Mailaender** [comment]
These metadata and program launcher files should be maintained upstream. It is just https://github.com/assaultcube/AC/pull/453 is ignored because the project is not well maintained.

Yes, the project license should also include the asset licenses. I didn't find a good summary about which license is actually used, so I left that blank.

**Comment by theonlypwner** [comment]
Does the folder have to be called `freedesktop`, or can this be changed?

I would probably prefer something like `.freedesktop`, similar to `.github` to help separate it from the other 'core' project folders.

And if it can be changed, we'd have to decide which is best: `.freedesktop`, `.flatpak`, or `.flathub`.

**Review by theonlypwner — CHANGES_REQUESTED** [review]
Does the folder have to be called `freedesktop`, or can this be changed?

I would probably prefer something like `.freedesktop`, similar to `.github` to help separate it from the other 'core' project folders.

And if it can be changed, we'd have to decide which is best: `.freedesktop`, `.flatpak`, or `.flathub`.

Other than this, it's good to merge, and I will merge after this is addressed.

**Comment by Mailaender** [comment]
The folder can be changed, but a dot folder would make it invisible on Linux.

**Review by theonlypwner — APPROVED** [review]
I will merge, rename the folder to `.freedesktop`, and update the `project_license`.

**Pull request merged**
